name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t your-dockerhub-username/your-app-name .

      - name: Push Docker image
        run: docker push your-dockerhub-username/your-app-name

      - name: Deploy to DigitalOcean
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.DIGITALOCEAN_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"docker_image": "your-dockerhub-username/your-app-name"}' \
          https://api.digitalocean.com/v2/apps/deployments
